### ISSUE TITLE
Accessing globals

### ISSUE THREAD

**Issue by Dairyman** [doadin/Plexus#1]
Hi, this classic changes write/read now global variables

Change:
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Statuses/Heals.lua#L112-L114
To:
```Lua
local incoming = 0
if not Plexus:IsClassicWow() then 
     incoming = UnitGetIncomingHeals(unit) or 0 
end 
```

And
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Statuses/Absorbs.lua#L96-L98
To:
```Lua
local amount = 0
if not Plexus:IsClassicWow() then 
     amount = UnitIsVisible(unit) and UnitGetTotalAbsorbs(unit) or 0 
 end 
```

**Comment by doadin** [comment]
Thanks!
