### ISSUE TITLE
[Bug] out of range indicator

### ISSUE THREAD

**Issue by rdmqwerty** [doadin/Plexus#103]
**Describe the bug**
the feature that makes character boxes fade in and out with range seems to be bugged recently

**To Reproduce**
im not 100% sure how to reproduce it. sometimes it works correctly when im in towns and stuff. but after playing through a whole raid i noticed alot of instances where characters were in range but were faded out and instances where they were out of range but still full color. it might happen when they go in and out of range while in combat

**Expected behavior**
their nameplate in plexus usually fades out when out of range

**Desktop (please complete the following information):**
 - Version - 3.3.7-classic
 - Game Version - season of discovery

**Additional context**
i pulled this error from an error handler addon i have

1x bad argument #1 to '?' (Usage: local inRange = C_Spell.IsSpellInRange(spellIdentifier [, targetUnit]))
[string "=[C]"]: ?
[string "@Interface/AddOns/Plexus/Statuses/Range.lua"]:126: in function `UnitInRange'

**Comment by doadin** [comment]
Just pushed an update v3.4.0 please let me know if this fixes this issue. https://github.com/doadin/Plexus/commit/264dbcc2c3e7db660587ef9a22971de738cfd098

**Comment by rdmqwerty** [comment]
it looks like this fixed some of the issue. i am noticing that dead targets are still faded out as out of range even when they are in range for a res
