### ISSUE TITLE
[Bug] /plexus command not working

### ISSUE THREAD

**Issue by rdmqwerty** [doadin/Plexus#104]
**Describe the bug**
typing /plexus in the chat window does not open up the options menu

**To Reproduce**
1. type /plexus in chat

**Expected behavior**
i expect /plexus to open the options menu

**Desktop (please complete the following information):**
 - Version - 3.3.7-classic
 - Game Version - season of discovery

**Additional context**
i pulled this error from an error tracking addon i have

3x Interface/AddOns/Plexus/Core.lua:786: attempt to index field 'optionsPanels' (a nil value)
[string "@Interface/AddOns/Plexus/Core.lua"]:786: in function `ToggleOptions'
[string "@Interface/AddOns/Plexus/Core.lua"]:709: in function `?'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:5034: in function `ChatEdit_ParseText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4686: in function `ChatEdit_SendText'
[string "@Interface/AddOns/Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:4722: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:120_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:120_OnEnterPressed"]:1>

**Comment by doadin** [comment]
This should be fixed in v3.3.9 https://github.com/doadin/Plexus/commit/8868d20e9dc46450076e7a2ca3034b5e783890ad
