### ISSUE TITLE
[Bug] debuff indicators not working

### ISSUE THREAD

**Issue by rdmqwerty** [doadin/Plexus#105]
**Describe the bug**
i have some debuff indicators for each debuff type (magic/disease/poison/curse) and those are not currently working

**To Reproduce**
1. setup a debuff indicator for magic
2. get a magic debuff on yourself
3. observe that it did not show up in plexus

**Expected behavior**
i expect the debuff indicators to show up when the applicable debuff is applied

**Desktop (please complete the following information):**
 - Version - 3.3.7-classic
 - Game Version - season of discovery

**Comment by rdmqwerty** [comment]
after playing some more, it seems like all of my indicators are no longer functioning. not only debuff ones

**Comment by Spotnick2** [comment]
It's worst than that in SOD.. /plexus doesn't work at all and there is no debuff on the grid at all.

**Comment by doadin** [comment]
I don't play classic but I tested self castable buffs on a character in classic and they showed up please let me know if you still have issues after updating to v3.3.9, whcih I just released to fix some issues.

**Comment by rdmqwerty** [comment]
i just downloaded the new version and it looks like everything is working for me. i tried out some buff indicators i have setup and went into combat to get debuffs and those showed up as well
