### ISSUE TITLE
[Bug] Lua errors on install - Background shown only, no player unit frame

### ISSUE THREAD

**Issue by Irenside** [doadin/Plexus#107]
35x Plexus/Frame.lua:146: attempt to index field 'db' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:674: in function <Blizzard_FrameXML/RestrictedFrames.lua:673>
[string "@Blizzard_FrameXML/RestrictedFrames.lua"]:812: in function `CallMethod'
[string "   RegisterUnitWatch(self)
   self:SetAttribute("*type1", "target")
   self:SetAttribute("useparent-toggleForVehicle", true)
   self:SetAttribute("useparent-allowVehicleTarget", true)
   self:SetAttribute("useparent-unitsuffix", true)

   local header = self:GetParent()
   if header:GetAttribute("unitsuffix") == "pet" then
      self:SetAttribute("useOwnerUnit", true)
      self:SetAttribute("unitsuffix", "pet")
   end

   local click = header:GetFrameRef("clickcast_header")
   if click then
      click:SetAttribute("clickcast_button", self)
      click:RunAttribute("clickcast_register")
   end

   header:CallMethod("initialConfigFunction")

   self:SetWidth(36)
   self:SetHeight(36)
   self:SetAttribute("initial-width", 36)
   self:SetAttribute("initial-height", 36)
   local attr = self:GetAttribute("*type2")
   if attr == "togglemenu" or attr == nil then
      self:SetAttribute("*type2", "togglemenu")
   end
"]:19: in function <[string "   RegisterUnitWatch(self)..."]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/RestrictedExecution.lua"]:483: in function <...aceBlizzard_FrameXML/RestrictedExecution.lua:446>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:116: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:110>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:173: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:130>
[string "@Blizzard_FrameXML/SecureGroupHeaders.lua"]:495: in function <...faceBlizzard_FrameXML/SecureGroupHeaders.lua:394>
[string "=[C]"]: in function `Show'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:82: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:

**Comment by doadin** [comment]
should be fixed: https://github.com/doadin/Plexus/commit/4acf2c0360dd0c61fe1f0d9b50e342159c1fc0ff included in v3.4.2 if you still have issues after updating please feel free to repoen or make a new issue report, thanks!
