### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tiff79** [doadin/Plexus#16]
Thankyou very much for doing this addon!

**Describe the bug**
Plexus -> layout -> layout padding

In grid I had this set to "0" (which resulted in a thin line around each of frames on my grid (i set this to a colour for when i have that person targetted).

I copied over my settings from grid (via plexus in game dialogue). Now in Plexus the right hand edge of each grid frame is missing unless I set layout padding to 1 (from previously working 0 in grid). 

**Screenshots**
.
(see pic with white right edge missing)

https://imgur.com/a/GmHC29U

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] win10
 - Game Version [e.g. Retail v8.3.0] current retail

thank you very much

**Comment by doadin** [comment]
Right off the top of my head rq, I can think of one possible reason. Plexus has a resource bar option that grid does NOT have. This resource bar does overlap with things like indicators, possible borders like this too. Do you have resource bar enabled and on right side by chance?

**Comment by tiff79** [comment]
Hi, Thanks for replying.

No I don't have the resource bar enabled (just double checked)... I've only installed plexus and removed grid today, I've changed no settings at all so  its exactly as per my grid install (apart from having to alter the layout padding from 0 to 1 to get the missing right hand line around the frames - as per this bug.

I remember grid also had this exact bug early in bfa but I fiddled with some settings back then possibly in the icon options tab and made it go away... (so the bug was still there but just not showing on my own set up).

thanks again

**Comment by doadin** [comment]
https://imgur.com/a/B2WnMKH
Is what I am seeing(inner white border goes on/off as per target) is this different from your settings?

**Comment by tiff79** [comment]
I think I see the issue now.. I have the scale set to 90% (as I found 100% too big) the bug goes away if I change the scale to 100%.. the bug comes back if I set to 90% - with the 2 other settings I use (unit spacing 0 and  layout padding 0).

Currently if I want to keep the 90% scale I have to alter layout padding from 0 to 1 to get the right side of the border to show.

Does that make sense? Sorry if i'm not explaining very well!

**Comment by doadin** [comment]
yes I get it, can you tell me what resolution your playing on including render scale if used?

**Comment by tiff79** [comment]
1920 x 1080 and 100% resolution scale

**Comment by doadin** [comment]
There are comments here:
https://www.wowinterface.com/downloads/fileinfo.php?id=5747&so=DESC#comments
about ui scale and how with different scaling 1 pixel in game is could not be 1 pixel for the monitor, basically. Its interesting how it works. Im going to leave this open for a bit in case I can find a solution, if there is one.

**Comment by tiff79** [comment]
Thanks! 👍 
I found a solution for my end anyway as if I set the scaling to 95% I can have everything else set as I wanted and it all works.
Big thanks for taking on this addon, great work:)
