### ISSUE TITLE
[Bug] Bottom indicators alignment

### ISSUE THREAD

**Issue by a2line** [doadin/Plexus#17]
As we can't use dynamicindicators, I'm trying embeded side indicators (all showing with the same buff) and all four bottom indicators are not centered (a bit more up and right), any idea why?
![image](https://user-images.githubusercontent.com/10353895/96357918-f059f980-1101-11eb-8172-a06d33a56e1a.png)

**Comment by doadin** [comment]
If by "I'm trying" you mean you are editing the source, I have added these indicators in a newer version, if you mean the ones I added are not aligned then please correct me, Though in my testing I think mine where more aligned. Either way let me know.

**Comment by a2line** [comment]
No, no editing of sources. I was using last build while discovering your wonderfull Plexus! Here it is again when I put corner size to 6 
![image](https://user-images.githubusercontent.com/10353895/96374066-c55abe80-1170-11eb-8551-a0df5183cd42.png)

**Comment by a2line** [comment]
I was also expecting that removing the side indicators 4 would remove the more centered one. Positions looks not intuitive at all. You should perhaps reorder them before they are too much used. For eg. always use 

2
1 4
3
… with clockwise rotation of this for all sides? 
Here is a screenshot with the 4 side indicators 1 2 3 only (all current side indicators 4 removed)
![image](https://user-images.githubusercontent.com/10353895/96374356-92192f00-1172-11eb-9cb6-3226e3ea218e.png)

**Comment by doadin** [comment]
What size is your frames? each middle one starts at 1 as far as I Know and the others a aligned around that one Ill look into it.

**Comment by a2line** [comment]
Frame is 32×32.

**Comment by doadin** [comment]
Thanks, im looking into makeing the changes will try to get a fix out soon like you said before poeple start using all these indicators.

**Comment by doadin** [comment]
Ok, hopefully v2.0.28 is better.

**Comment by a2line** [comment]
Bottom indicators alignment looks good, thank you for that! The logic of placement still echaps me, for “top” it's 2 in the middle, for “bottom” and “right” it's 4 and for “left” it's 3. Here is the pattrern in version 2.0.29:
Bottom
   2
3 1 4

Left
2
1 4
3

Right
   2
4 1
   3

Top
2 1 4
   3


   2 1 4
2    3    2
1 4    4 1
3    2    3
   3 1 4

What I described on previous post would be:
   3 1 2
2    4    3
1 4    4 1
3    4    2
   2 1 3
And now that I see it, putting 2 in the center is perhaps a better idea, because it makes clockwise little spiral counting from 1 to 4 and it's quite simple to remember for each side:
   3 1 4
4    2    3
1 2    2 1
3    2    4
   4 1 3

**Comment by doadin** [comment]
Ok so that covers all the top bottom left right how about the topleft etc etc?

**Comment by doadin** [comment]
https://github.com/doadin/Plexus/commit/dc6957d4288e6462c1ae2c29ebd61d6579577173 is what I got now btw.

**Comment by a2line** [comment]
Right side is not good, you must switch 2 and 4. Trying corners alternative right now, never used them.

**Comment by doadin** [comment]
github wont keep the formating but this is what it currently looks like 
```
13          3 1 4          2 1
 2              1                 3

4                                3
1 2                          2 1
3                                4

2               2                2
13          4 1 3           3 1
```

**Comment by doadin** [comment]
roughtly

**Comment by doadin** [comment]
image probably better https://imgur.com/a/joP7xpt

**Comment by a2line** [comment]
For corners, applying the same “spiral” idea can be good. For formatting I use &amp;nbsp; (non-breakable spaces). I can do the full on for documentation if you want.
1 2    3 1
3          2

2          3
1 3    2 1

**Comment by a2line** [comment]
**1 2**   3 1 4   **3 1**
**3**         2         **2**

4                    3
1 2              2 1
3                    4

**2**         2         **3**
**1 3**   4 1 3   **2 1**

**Comment by doadin** [comment]
I think thats what I have in https://github.com/doadin/Plexus/commit/5a4fcd73bad926847a34b2ddf60a2be42df0d6a9 now.

**Comment by a2line** [comment]
And now that we have corner with sides we want to read first row 1 2…4 1 2, top side with 3 in the middle, isn’t it?! Dunno if you wan't to change again. Is its far better than before, Thank you! Try last commit you posted to verify.

**Comment by doadin** [comment]
5a4fcd73bad926847a34b2ddf60a2be42df0d6a9 the last commit I posted should have all the indicators as per your post. I think. Is this the final?

**Comment by doadin** [comment]
Happy to make changes you think are better.

**Comment by a2line** [comment]
**1 2**   4 1 2   **3 1**
**3**         3         **2**

2                    4
1 3              3 1
4                    2

**2**         3         **3**
**1 3**   2 1 4   **2 1**

so circular permutation of 2 3 4 gives:
    -- left/right up/down
    Top = { "TOP", 1, 1 },
    Top2 = { "TOP", 6, 1 },
    Top3 =  { "TOP", 1, -4 },
    Top4 = { "TOP", -4, 1 },
    -- left/right up/down
    Bottom = { "BOTTOM", 1, 0 },
    Bottom2 = { "BOTTOM", -4, 0 },
    Bottom3 = { "BOTTOM", 1, 5 },
    Bottom4 = { "BOTTOM", 6, 0 },
    -- left/right up/down
    Left = { "LEFT", -1, -1 },
    Left2 = { "LEFT", -1, 4 },
    Left3 = { "LEFT", 4, -1 },
    Left4 = { "LEFT", -1, -6 },
    -- left/right up/down
    Right = { "RIGHT", 1, -1 },
    Right2 = { "RIGHT", 1, -6 },
    Right3 = { "RIGHT", -4, -1 },
    Right4 = { "RIGHT", 1, 4 },

**Comment by a2line** [comment]
I prefer that last one because we read the 1st row from left to right (perhaps not everybody on earth…) and apply that scheme to other. And 2 or 3 in the middle is not intuitive but the whole thing is, we can't have everything. Thank's for your time on this.

**Comment by doadin** [comment]
ok c1d9771420b18cfdc76a543565eb2d28c0618f3e should now be like your last post.

**Comment by doadin** [comment]
And I don't mind appreciate the input.

**Comment by doadin** [comment]
if you wana just double check rq that would be appreciated make sure everything still aligns.

**Comment by a2line** [comment]
I have checked ingame the code I gave, so just by reading your last commit diff it looks good for me.

**Comment by doadin** [comment]
ok, awesome ill push this update through then. and close this up. If you notice anything more feel free to open another. always welcome to input/thoughts/ideas.
