### ISSUE TITLE
[Request] GridStatusDirectionArrows

### ISSUE THREAD

**Issue by a2line** [doadin/Plexus#18]
I was cleaning my Grid sub-addons and see I still have GridStatusDirectionArrows that was marvelous to quickly know where out of range players (who often need heals!) are and how far. It helped a lot to take better decisions while healing. We can minimize our movements (and that way heal more) by taking instantly the right directions and also estimate the time of the round-trip, so we know “if it would be insightfull to reach that player or if it is at a loss for the raid”.

Is there a way to have a similar distance mesurement + arrow system working in Plexus?

**Comment by yoshimo** [comment]
I doubt that it makes sense to port this due to changes from Patch 7. 0.1 4 years ago:

GetPlayerMapPosition
(2016-10-25): Returns nil while inside a restricted area (instance/battleground/arena).

So you can't know where people are when it is needed the most.

**Comment by doadin** [comment]
This is true they serve very little use I was still looking into adding it but because of its little use its very low priority.

**Comment by doadin** [comment]
its on the todo list so just gonna close this I can keep track of it from there.
