### ISSUE TITLE
Resource bar - Only Show Healers Bars doesn't work when solo

### ISSUE THREAD

**Issue by ywfn** [doadin/Plexus#19]
I have my resource bar set to only show mana bars, and to only show healers bars.

Playing a mage, when I'm not grouped, the mana bar shows anyway.  But if I join a party, the mana bar immediately goes away.  Comes back when I leave the party.  Seems like the "Only Show Healers bars" option doesn't work properly when not grouped.

**Comment by doadin** [comment]
Fixed: c4bb2ddb9ca87bc232d4bd79c661d8edfc62891b
