### ISSUE TITLE
More global access

### ISSUE THREAD

**Issue by Dairyman** [doadin/Plexus#2]
Found few more.

https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L73
```Lua
local  function Icon_NewIndicator(frame) 
```
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L107
```Lua
local function Icon_ClearStatus(self) 
```
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L119
```Lua
local function Icon_SetStatus(self, color, text, value, maxValue, texture, texCoords, stack, start, duration) 
```
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L146-L147
`count` does not exist. Should that be `value`? 
\
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L155
```Lua
local function Icon_ResetIndicator(self, point, idx) 
```
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L229
```Lua
local function Icon_RegisterIndicator_Plus(id, name, point, idx) 
```
\
https://github.com/doadin/Plexus/blob/4e9b19b8a3d2eb6d8659e19d90eb4fa996a1948f/Indicators/Icon.lua#L240
```Lua
local function Icon_RegisterIndicator(id, name, point, iconsMore1, iconsMore2) 
```

**Comment by doadin** [comment]
Believe it or not but I actually did have these in before but in development I must have changed it and forgot to add it back when I fix the issues I was having. Thanks for noticing. I believe I have corrected everything you have brought up so far. If you see any more let me know, much appreciated!
