### ISSUE TITLE
[Bug] Plexus v2.0.35 Lua Errors in Layout.lua and Layouts.lua

### ISSUE THREAD

**Issue by Tetsemi** [doadin/Plexus#20]
`4x Plexus\Layouts.lua:245: '<eof>' expected near 'end'

Locals:`

`2x Plexus\Layout.lua:1010: attempt to get length of local 'layout' (a nil value)
[string "@Plexus\Layout.lua"]:1010: in function `LoadLayout'
[string "@Plexus\Layout.lua"]:608: in function `PostEnable'
[string "@Plexus\Core.lua"]:342: in function <Plexus\Core.lua:334>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Plexus\Core.lua"]:738: in function `EnableModules'
[string "@Plexus\Core.lua"]:545: in function <Plexus\Core.lua:538>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory\ArkInventory-30943.lua"]:10246: in function `LoadAddOn'
[string "@ArkInventory\ArkInventory-30943.lua"]:10261: in function `BlizzardAPIHook'
[string "@ArkInventory\ArkInventory-30943.lua"]:2632: in function <ArkInventory\ArkInventory.lua:2602>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>`

**Comment by doadin** [comment]
Hello, yes its a bug in the build system that hopefully e6d8c6da97cf3535ac3c64416f47382924082e6c fixes. Commit and build pushed will know soon.

**Comment by Tetsemi** [comment]
Also, reverting just the Layouts.lua to the 2.0.34 version fixes both errors, in case that helps.

**Comment by doadin** [comment]
2.0.36 is out now and should be working.

**Comment by Tetsemi** [comment]
Confirmed 2.0.36 no errors, thank you.
