### ISSUE TITLE
Center Text 3 off frame [Bug]

### ISSUE THREAD

**Issue by stevietv** [doadin/Plexus#23]
**Describe the bug**
Center Text 3 shows below the unit frame, spacing between text is too much

**To Reproduce**
1. go to settings
2. go to frame > text options
3. enable center text 2 and center text 3
4. in indicators add unit name to all three center text indicators (as a test)

**Expected behavior**
expect to see all three text lines on the unit frame. When enabling only center text 2 the center text is shifted up, but when enabling center text 3 the other two indicators are not moved to allow for all three lines of text.

**Screenshots**
![image](https://user-images.githubusercontent.com/1117625/97495713-416eb680-1968-11eb-8646-ace2393e4c77.png)
As can be seen, the ... underneath the frame is the third line of text.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.0.39
 - Game Version [e.g. Retail v8.3.0] 9.0.1

**Additional context**

**Comment by doadin** [comment]
sorry for the late reply. I didn't notice this before sorry about that, im looking into it.

**Comment by stevietv** [comment]
> sorry for the late reply.

22 hours isn't late in my book! thanks for looking into it!

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Plexus/commit/486b6f07a129b3fd822f31a5cdce811dc2332973 look for v2.0.44. At least I hope that fixes it? Its on frame now and no matter what combo of text 2 or 3 enabled I did it always was layout:
Text1
Text2
Text3

Let me know if you still have issues.
