### ISSUE TITLE
[Request] Manabar invert / Phase Reason Color

### ISSUE THREAD

**Issue by hobulian** [doadin/Plexus#24]
Hope there's option for manabar invert just like healthbar

Also It will be nice there's configure for phase icon(Interface\\TargetingFrame\\UI-PhasingIcon) color according to it's phasing reason(for example, Warmode(red)/ shard(normal)/Chromie time(blue))

**Comment by doadin** [comment]
you mean invert foreground/background color? There is, Plexus > Frame > Extra Bar Indicator Options > Invert Extra Bar Color. It invers the bar as a whole just like health does.

I like the idea of colors what color is "normal"?

**Comment by hobulian** [comment]
Oh there was option for that. Thanks.

normal means default color r,b,g = 1,1,1
I think.

**Comment by doadin** [comment]
1,1,1 is white why not maybe green?

**Comment by doadin** [comment]
well correction in WoW use 1,1,1 is black

**Comment by doadin** [comment]
I added more colors now.

**Comment by hobulian** [comment]
> I added more colors now.

I checked but icon color wouldn't changed.
https://imgur.com/a/wjtEKxO
This is what i meant. Bigger phase icon is plexus and smaller is phase icon weakauras.
When warmode phased icon color changed to red..

r,b,g = 1,1,1 means 255/255/255 I mis-wrote value.

**Comment by doadin** [comment]
sorry I thought you meant like box indicators color not icon color. Im not sure about changing the icon. is the weak aura online?

**Comment by hobulian** [comment]
https://wago.io/z5IYG4-CN

Here's the link

**Comment by hobulian** [comment]
I hope there is option for background color at Extra bar indicator options.
