### ISSUE TITLE
[Bug]with names

### ISSUE THREAD

**Issue by Addonman** [doadin/Plexus#25]
In raid names most likely russian  are shown as rectangles

![Plexus](https://user-images.githubusercontent.com/2686143/97807738-db817800-1c62-11eb-9f76-bf9bf2143557.PNG)

**Comment by doadin** [comment]
Have you tried using a different font?

**Comment by Addonman** [comment]
Seems font issues with friz Quadratta dd.Fixed with change of font.

**Comment by doadin** [comment]
fe21286005b351b2d9c18ce9c3958668aefdcdd4
