### ISSUE TITLE
[Request] Taunt

### ISSUE THREAD

**Issue by Matt-One** [doadin/Plexus#26]
As a tank, i have the threat border in red when other player take the aggro of the mob im tanking, Is it possible to have an option for taunt? Something like TauntMaster, so when i see the red border, i can click the frame of that player and taunt the mob also if the player is targetting me or a player (if healer).

Thank you :)

**Comment by doadin** [comment]
so you have two options, the addon clique or plexusclicksets. With those you can create a macro/bind for whatever key you want and have the same functionality of TauntMaster if you make a macro in one of those like:
`/cast [@mouseovertarget] Taunt`

The player/unitframe needs to be targeting the thing they have threat on though. Which is the same for TauntMaster whcih is why you didnt ask but imgona give my 2 cents anyways this is not something you can rely on nor should really use. Theres no guarantee that you are going to taunt the right target or anything at all. You would be better off using name plates that show threat.
