### ISSUE TITLE
[Request] Migration Table Wiki Page

### ISSUE THREAD

**Issue by yoshimo** [doadin/Plexus#27]
Since there are probably as many grid reliant status plugins as there are handynotes modules i think we should collect the existing plugins and give people tips on what to do with them

Grid-Plugin Name
Plexus-Plugin Name , if available
Done by Plexus itself?
Future Plexus support?
Migration compatibility

something like that.
On a related note, aren't status plugins small enough to merge them for a better oob experience and less management?

**Comment by doadin** [comment]
interesting. working on that a little now.

**Comment by doadin** [comment]
im sure it could use some work but : https://github.com/doadin/Plexus/wiki/Migration-Table

**Comment by doadin** [comment]
as far as merging some are small some are not and to keep with the small modular design of grid I try not to add TOO much but really I play with basically plexus and GridStatusRaidDebuff2 + the expansions list that goes with it. I do use clique which gridclicksets/plexus click sets could replace but like others im sure clique is very common and I heard of it first and have been using clique for a long time now, way before I started messing with addons.

**Comment by yoshimo** [comment]
Haven't looked inside the .toc files but on the first glance i couldn't match these folders:

> GridAlternativeLayouts
> GridAutoSizeLayout
> GridConfigIcons
> GridCustomLayouts
> GridFilterLayout
> GridHomeParty
> 
> GridIndicatorBar
> GridIndicatorBorderTexts
> GridIndicatorBuffBar
> 
> GridLayoutByRole
> GridResizeFrames
> 
> 
> GridStatusAncientBarrier
> GridStatusControlPipes
> GridStatusDungeonRole
> GridStatusEmphasize
> GridStatusEnemyTarget
> GridStatusExternals
> GridStatusFastHealth
> GridStatusHRTargets
> GridStatusHealTrace
> GridStatusHealingReduced
> GridStatusItemLevel
> GridStatusRaidIcons
> GridStatusShield
> GridStatusSwiftmend
> GridStatusTotalAbsorbs
> GridStatusWeakenedSoulDebuff
> 
> GridTargets
> gridstatusabsorbshields
> 

Maybe for people using grid2 we could list 

- Grid2TrailOfLight
- Grid2StatusAbsorbs
- Grid2Guarm
- Grid2StatusPhasing
- Grid2SurvivalBuff

**Comment by doadin** [comment]
That is a lot of stuff to go through. I have made some updates to the plugins and migration wiki but I dont think its going to go much further from me. I am 100% open to changes though it you want to post them in some way I can review.

**Comment by yoshimo** [comment]
You don't have to list Addons twice. WoWAce and Curse are using the same backend
https://www.wowace.com/projects/grid-indicator-corner-icons & https://www.curseforge.com/wow/addons/grid-indicator-corner-icons have the same author and the same Project ID

**Comment by doadin** [comment]
unintentional duplicate I also found one other, thanks!

**Comment by yoshimo** [comment]
GridstatusAncient barrier has overlaps with PlexusStatusRD_MOP and GridStatusRD_MOP, but i'm not sure if they show the same level of detail.
