### ISSUE TITLE
[Bug] Plexus does not copy all Grid profiles

### ISSUE THREAD

**Issue by johnfriedrich** [doadin/Plexus#28]
Hey, I used Grid for countless years and bit sad that it stopped working. Looked into Grid 2, but wasn't able to get the same UI result like with Grid. So I was looking into a "quick" fix by using Plexus. Installed it (2.0.65) and was prompted an import Grid settings.
I clicked ok, stopped wow and restartet it.

I have a few Grid profiles, but no profile was copied over. I restarted again and activated Grid and Plexus at the same time and this time one profile got copied over. But that was the wrong one. I do know, that some profiles are created with this character and some other by others. 

1. Enable Grid and Plexus.
2. Hit import settings in the prompt dialog
3. restart wow
4. Open Plexus profiles
5. No or just one Grid profile was copied over

**Expected behavior**
All Grid profiles copied over

**Screenshots**
My Grid profiles
![image](https://user-images.githubusercontent.com/4679374/98466633-f60ea080-21d0-11eb-9698-08b8abf819c0.png)
 Just "Shaman" was copied over

**Desktop (please complete the following information):**
 - OS: 20H2 Pro 64
 - Version 2.0.65
 - Game Version 9.0.1

**Additional context**

**Comment by Anduviel** [comment]
I couldn't copy anything useful, so started new

**Comment by doadin** [comment]
probably just going to remove the feature. I got it to copy some of my settings when I switched but seems to be very unstable.

**Comment by yoshimo** [comment]
Was a nice feature though that could have helped the transition progress.
