### ISSUE TITLE
[Bug] [Classic] UI freezes when players join/leave/move on large raid groups

### ISSUE THREAD

**Issue by tstirrat** [doadin/Plexus#29]
**Describe the bug**

**Note:** I disabled all other addons and reset my Plexus profile to default to ensure this is not some other addon/WA.

I get a UI freeze each and every time the raid composition changes when the raid size gets above approx 20 players. It can be 500ms-1500ms

**To Reproduce**
1. Add 39 people to a raid
2. instruct one member to join and leave the raid repeatedly, or move someone in raid repeatedly

The entire game hangs for a 500ms - 1500ms when the raid member joins/leaves/moves

**Expected behavior**
The UI should not hang

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Version: v2.0.70-classic
 - Game Version: Classic 1.13.5
 - Specs: Macbook Pro, 2.3 GHz Quad-Core Intel Core i7, 32GB Ram, 513GB SSD

**Comment by doadin** [comment]
Hopefully fixed: 37a030d644cb9a80f64244571036ce02a53209d0 . Commit is in v2.0.71. When you update to that version let me know if you still have issues.

**Comment by tstirrat** [comment]
Thanks! I'll report back

**Comment by tstirrat** [comment]
Unfortunately it's still an issue in `2.0.71-classic`. No real improvement, it's still hanging for approx 1 second each change

**Comment by doadin** [comment]
I should have a fix that should make the situation much better coming soon.

**Comment by doadin** [comment]
related: https://github.com/doadin/Plexus/issues/30

**Comment by doadin** [comment]
Hopefully fixed: 0275aa42525a2103b5eeb4f3c4a3b7666949ff4b in v2.0.72.

**Comment by tstirrat** [comment]
It's definitely better, still some lag, but it's more like 250ms-500ms now, and is manageable.

Thanks
