### ISSUE TITLE
[classic] resource bar disappears

### ISSUE THREAD

**Issue by ssateneth** [doadin/Plexus#3]
Plexus 1.7.4 classic

The frame resizing works fine as of 1.7.4 but the glitch with the resource bar still happens. See video. I do not get any lua errors when this bug happens. I made sure lua errors is showing by doing /run werbewlrhewh (which should be invalid and pop an error)

https://i.imgur.com/2TEiKUq.gifv

I reset profile twice then reload ui. Enabled resource bar status, enabled resource bar indicator (it shows on bottom), move to right side (works fine), change frame width (works fine) then frame height (doesn't work correctly as resource bar doesnt resize vertically). I reload UI and now the resource bar will not show on left / right, only top / bottom.

I clear profiles again twice and reload ui. This time, I do the bar status and indicator again and change from bottom to right again, change frame size the same as before, but this time I change the center text font size. Once I change the font size, I lose the resource bar again.

**Comment by doadin** [comment]
I just pushed a few versions v1.7.5 should have a fix im hoping. (latest is now 1.7.6)

**Comment by ssateneth** [comment]
Looks good to me! Haven't been able to get the resource bar or corner dots to glitch out yet, so consider the matter closed. I'll re-open if I have future issues.
