### ISSUE TITLE
[Bug] 40man raid leavers/joiners causes massive lag of 1-5 sec in ICC

### ISSUE THREAD

**Issue by Voxxel** [doadin/Plexus#30]
**Describe the bug**
In ICC if I join any rare-hunting 40man raids there's a huge lagspike for every member joins or leaves after defeating a boss. If I turn off Plexus, there's no lag of course.

**Desktop (please complete the following information):**
 - OS: Win10 pro
 - Version: latest
 - Game Version: latest

**Additional context**
I'm not experienced this in other environments like Nyalotha Mythic raiding, but that's only 20 man.

**Comment by doadin** [comment]
I think I have a fix, working on finishing it up and should have it out soon.

**Comment by doadin** [comment]
related: https://github.com/doadin/Plexus/issues/8

**Comment by doadin** [comment]
Hopefully fixed: 0275aa42525a2103b5eeb4f3c4a3b7666949ff4b in v2.0.72.
