### ISSUE TITLE
[Bug] corner indicators location broken in last patch 

### ISSUE THREAD

**Issue by tiff79** [doadin/Plexus#31]
**Describe the bug**
I''ve used the bottom left and bottom right corner indicators for years (i ported from  grid) everythings been working in Plexus. I have never used the extra corner indicators.

The corner indicators were exactly in the corners and now are floating above where they should be.

I haven't changed any settings.. I check everyday for plexus updates and this was working as normal when I last logged to wow a few days ago. Tested and confirmed broken on both bottom corner indicators. Not tested the top ones yet.

**Screenshots**
https://imgur.com/a/xUGJMOr

(green dot indicator showing renew...use to be in the corner and now is above the corner position for some reason).

Plesux version 2.0.80

**Comment by doadin** [comment]
I recently made a change that if the extra bar is enabled indicators of any kind would move up to be out of the way of the extra bar, if you disable extra bar they should move back down. Would you rather the indicators/extra bar cover each other?

**Comment by tiff79** [comment]
I’ve never used /enabled or seen an extra bar. Will have a search when I’m next on wow tomorrow.
Thanks!

**Comment by doadin** [comment]
Indicators without extra bar:
https://i.imgur.com/rlCpqmA.jpg
Indicators with extra bar but no status on extra bar:
https://i.imgur.com/J0g9hLX.jpg
Indicators with extra bar and resource status on extra bar:
https://i.imgur.com/y9Pg1cz.jpg

**Comment by doadin** [comment]
So I recently added in an option to go back to the old behavior so should be fine either way may just need to adjust setting based on your prefference, gonna close this now. If you still have issues or anything feel free to reopen or make a new issue. thanks!
