### ISSUE TITLE
[Bug] Strange bar shown on spec change

### ISSUE THREAD

**Issue by Lej** [doadin/Plexus#32]
**Describe the bug**
When "Enable spec profiles" is enabled, and a spec change causes a profile change, the frames show a bar at the bottom until the UI is reloaded, even though no bar is enabled.

**To Reproduce**
1. Go to "Plexus > Profiles" and tick "Enable spec profiles.
2. Setup a change of profile. In my case Balance uses one profile and Restoration another:
![image](https://user-images.githubusercontent.com/2363121/99914471-e4afb300-2cfd-11eb-82c3-e391d8781ef0.png)
3. Change spec. In my case from Balance to Restoration. A strange bar shows up at the bottom of the frame:
![image](https://user-images.githubusercontent.com/2363121/99914521-4112d280-2cfe-11eb-91c9-49abb8e3f3c7.png)
4. A workaround is to reload the UI which removes the strange bar:
![image](https://user-images.githubusercontent.com/2363121/99914546-643d8200-2cfe-11eb-9328-7dff2e7223f1.png)

**Expected behavior**
The strange bar should never show up since I have no bars enabled.

**Desktop:**
 - OS: Windows 7
 - Version: 2.1.15
 - Game Version: Retail v9.0.2 (36710)

**Comment by doadin** [comment]
so you don't have the extra bar enabled for either profile?
does the bar go away after time? if you change forms etc or is reload the only way it goes away?

**Comment by Lej** [comment]
> so you don't have the extra bar enabled for either profile?

Exactly. No extra bar is enabled for either profile.

> if you change forms

No. Changing form does not make it go away.

> is reload the only way it goes away?

Yes. At least it is the only way I have found to make it go away.

**Comment by Lej** [comment]
Correction, "Enable Extra Bar Requires ReloadUI" **was enabled**. Disabling solved the problem.

This fixes the problem for me. Still, don't think the extra bar should show up, and then disappear with a reload.

**Comment by Lej** [comment]
I tried enabling/disabling "Enable Extra Bar Requires ReloadUI" a few times, reloading UI after every enabled/disable. Managed to get the bar to show up once while the "Enable Extra Bar Requires ReloadUI" was enabled. Enabling it and disabling it fixed it again. I have not been able to reproduce it consistently.

**Comment by doadin** [comment]
Hoping https://github.com/doadin/Plexus/commit/3a3170bf085c30ee1a434864097ef6f0a1d7b02c will fix this. Sorry it has taken so long if you stuck with me I appreciate it very much! If this doesn't or you have any other issue please don't hesitate to let me know.
