### ISSUE TITLE
[Request] Colored Buff indicators based on buff time remaining

### ISSUE THREAD

**Issue by jpreese** [doadin/Plexus#34]
Thank you so much for Plexus, I maintained my own Grid fork for a long time--fixing it every expansion. Yours seems to work pretty well out of the box, but one _huge_ feature for me was changing colors based on buff durations.

e.g. Set the `Top Right Corner` to `Buff: Rejunvenation` and it would start green, then change to yellow at X seconds left (or some %) then red at X seconds left.

When using Center Text (and **Center Text 2**! (which let you put text under the persons name in the frame), it was nice to see the numerical duration.

GridStatusHotter: https://www.curseforge.com/wow/addons/gridstatushotter did most of this, but I haven't been able to get it to work with Plexus yet.

**Comment by doadin** [comment]
Im not familiar with that plugin but is what you are looking for not covered by:
1. Plexus > Status > Auras > Show Advanced
+
2. Plexus > status >auras > (as a sample) Buff: Rejunvenation > Color > Time left ?

**Comment by jpreese** [comment]
@doadin .. I didn't even see that. And here I was ready to post I got GridStatusHotter to work by using `AuraUtil.FindAuraByName()`.

Before I go down another potential useless rabbit hole, is there support somewhere for two Center Text? I'd like to keep Center Text for the player name, but then have a "Center Text 2" which was an option in another old Grid addon that let you put Text there as well.

**Comment by jpreese** [comment]
I just found it. Ignore me. Thanks for pointing that out. I apparently need to dig into the settings harder. All of this used to be addons, but its so much nicer being all built in!

**Comment by doadin** [comment]
:) I tried to add as much as I thought was good without adding too much bloat.

**Comment by doadin** [comment]
So is there any more I can help with or you good for now?

**Comment by jpreese** [comment]
Nope, I think that's everything! This addon is huge. I was never a fan of Grid2, so I'm glad to see you're keeping the Grid spirit alive.
