### ISSUE TITLE
[Bug] Ressource Bar doesn't show

### ISSUE THREAD

**Issue by Sekorhex** [doadin/Plexus#35]
**Describe the bug**
Ressourcebar doesn't show after the update.

**To Reproduce**
1. Go to '/plexus'
2. Click on 'Indicator'
3. Scroll down to 'Extra Bar'
4. Activate Ressource

**Expected behavior**
Show me Mana, Rage and other Ressources for any class.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/42946288/100650161-ca9c5300-3343-11eb-87ed-a550535ba2cb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2
 - Game Version: Retail 9.0.2

**Comment by OdessaGrimaldus** [comment]
I had this same issue, Sekorhex. ..For some reason the most recent update disabled the resource bar to show, and Doadin has answered this to another on curseforge, which fixed it for them and has for me aswell.

Plexus > Status > Resource > Enable 

I don't know why it was disabled for some reason, but this sure enough fixed things. I hope it does the same for you.

**Comment by doadin** [comment]
In a recent update I had changed a few things. The bar and the status used to be very tied together. In recent updates I have made updates to separate them to try and make it clearer that there is a bar with its own settings and a status with its own settings. Part of the reason for this change is the bar doesn't just do mana/rage etc any more it can now also be used for alternative power, and maybe more in the future.

**Comment by doadin** [comment]
Hopeful things are more clear now and I tried to make changes in a way that should no effect users setttings in the future and be mroe obvious when they get used to how it is now to then apply that to future changes, again maybe more bar options more statues that can use a bar....not sure what the future might hold.
