### ISSUE TITLE
debuff stacks

### ISSUE THREAD

**Issue by tiff79** [doadin/Plexus#39]
Has something changed with how to setup a debuff that shows stacks (eg bursting?)

Doesn't seem to be working for me.. shows burst is present but not how many stacks (despite having it set to show stacks).. (when tracked as center icon)

thanks

**Comment by tiff79** [comment]
doesn't seem to show any stacks... this is a bit of a problem...

**Comment by doadin** [comment]
Do you have it set via aura or raid debuff?

**Comment by tiff79** [comment]
Debuff.. I just did a ton of testing (via krosus searing brand debuff) and figured out it was text size/icon size settings... when text size is 5 no stack count shows
