### ISSUE TITLE
[Bug] Resource bar not working

### ISSUE THREAD

**Issue by Anduviel** [doadin/Plexus#40]
**Describe the bug**
Resource bar not working

I can test the resource bar perfectly but no matter how much I reload it won't show.
- status  extra bar is set to resource by default
- bottom icons are floating above an imaginary bar of something
- cannot find anything that helps the problem

**Comment by doadin** [comment]
you need to have the following set:
Frame > Extra Bar Indicator Options > Enable Extra Bar
Status > Resource > Enable
Indicators > Extra Bar > Resource
