### ISSUE TITLE
[Request]bring back the option to show a separate "tank row"

### ISSUE THREAD

**Issue by TurduckenMcNugget** [doadin/Plexus#43]
Grid used to have, back in MoP at least, an option which added a row above group 1 containing duplicate frames of anyone whose role was tank. The tanks still showed up in whatever group they were in, but this additional row made it very easy to see the tanks and their status.

I found an old screenshot which showed what it looked like; you can view it here [https://i.imgur.com/JPhQR00.jpg](https://i.imgur.com/JPhQR00.jpg)

**Comment by doadin** [comment]
You can likely achieve this using https://www.curseforge.com/wow/addons/plexuscustomlayouts .
