### ISSUE TITLE
grevious wound not showing

### ISSUE THREAD

**Issue by tiff79** [doadin/Plexus#45]
I can't get grevious wound stacks to show. I've set it up as per normal (eg the same way I have bursting stacks showing) but it just doesn't show. Hard to test much given it only shows up in keys.

I found an old post of someone with grid having the same issue and they fixed it by adding it by the spell id.. I tried that too and it didn't work.

v 2.1.38

**Comment by doadin** [comment]
Do you get the debuff to show at all? What spell id did you use?

**Comment by doadin** [comment]
It shows fine for me when I use the dungeondebuff plugin and it used id 240559

**Comment by tiff79** [comment]
I added it as a debuff (how I have for years with other debuffs I want to see). 
I tried adding it as its proper name "grevous wound" and as the spell id you list. Neither show at all.
[https://imgur.com/lEXiB4X](url)

**Comment by tiff79** [comment]
this was an error on my side. sorry.

**Comment by doadin** [comment]
No problem, I was just testing this again my self recently and didn't have any issues and was starting to wonder. As you can imagine kind of hard to find out the issue when you can only see the debuff in a 7+ key, was not looking forward to having to figure that out lol. Alls well that ends well.
