### ISSUE TITLE
TBC support

### ISSUE THREAD

**Issue by Jinnai** [doadin/Plexus#46]
Several errors pop up because Plexus:IsClassicWow() returns false on TBC Classic.

I suggest instead to `return WOW_PROJECT_ID ~= WOW_PROJECT_MAINLINE`

Another error that pops up:

`Plexus\Statuses\GroupBuffs.lua:199: attempt to concatenate field 'Arcane Intellect' (a nil value)
[string "@Plexus\Statuses\GroupBuffs.lua"]:199: in main chunk`

Looks like Arcane Intellect with id 1472 was removed in TBC, 1459 seems to work.

One more in Plexus\Indicators\Border.lua:26
The BackdropTemplateMixin is only added for wowtocversion > 90000

**Comment by doadin** [comment]
I don't have tbc access yet , I will update when I do.

**Comment by doadin** [comment]
should be working now.
