### ISSUE TITLE
[Bug] No auras?

### ISSUE THREAD

**Issue by sWxJaPkT** [doadin/Plexus#48]
**Describe the bug**
There is no druid MoTW in the TBC version of this addon. 
**To Reproduce**
Download 
https://www.curseforge.com/wow/addons/plexus/download/3305502

**Expected behavior**

**Screenshots**
https://i.imgur.com/PiBuCac.png

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. v1.5.6]
 - Game Version [e.g. Retail v8.3.0]

**Additional context**

**Comment by sWxJaPkT** [comment]
Sorry - no DRUID aura of MoTW

https://i.imgur.com/PiBuCac.png

**Comment by doadin** [comment]
That would be something found under group buffs, though I will also note that status has not been updated yet but will be soon.

**Comment by doadin** [comment]
Progress toward fix: still need to verify: 7ab6aaa955df7483752358143e5d714dfeceb349

**Comment by doadin** [comment]
should be fixed in newer version release just a min ago, let me know if you still have issues.
