### ISSUE TITLE
Lua error after latest update (v2.2.14)

### ISSUE THREAD

**Issue by Tetsemi** [doadin/Plexus#51]
Error loading Plexus\Help.lua

That's it, that's the whole error.

**Comment by Tetsemi** [comment]
I downloaded the Help.Lua file and placed it where the above error said it should be and everything is working now.  I don't know if the file just didn't get packaged with the latest release, but even a re-install didn't fix the issue I had to manually add the Help.lua file.

**Comment by doadin** [comment]
must have been a bad download all the release zips contain the help.lua file.
