### ISSUE TITLE
[Bug] An error occured after changing spec

### ISSUE THREAD

**Issue by Elnarfim** [doadin/Plexus#52]
**Describe the bug**
An error occured after changing spec
1542x Plexus\Statuses\Absorbs.lua:116: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "@Plexus\Statuses\Absorbs.lua"]:116: in function `?'
[string "@!DevilAlt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Alt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@!DevilAlt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Alt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@!DevilAlt\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Broker_Specializations\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...r_Specializations\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. v1.5.6]
 - Game Version [e.g. Retail v8.3.0]

**Additional context**

**Comment by doadin** [comment]
A possible fix for this has been released repopen if you still have issues.
