### ISSUE TITLE
[Bug] Extra (recource) bar indicator does not show for me

### ISSUE THREAD

**Issue by Anduviel** [doadin/Plexus#66]
Extra (recource) bar indicator does not show for me
it shows properly when testing, but I cannot enable or disable the extra bar on the bottom.
reloading does not help

**Comment by doadin** [comment]
Is this on retail, wrath, classic?

**Comment by Anduviel** [comment]
Retail

**Comment by doadin** [comment]
Do you have Status > Resource >Enable Set?
Also Indicators > Extra bar > Resource checked?

**Comment by Anduviel** [comment]
I have them still  and have used grid/plexus for ages. 
indicater is recource, on extra bar ande extra bar is turned  on in the frame window.
I am on a completely fresh blizz ui.
disabling all other addons but plexus does not help.2 reloading does not help.
So I am very puzzled with whats wrong.

What else can I do to solve this problem?

**Comment by Anduviel** [comment]
Thanks very much  I have found it, it was the status >recource > enable set in recources.

**Comment by doadin** [comment]
NP
