### ISSUE TITLE
[Bug] bugsack error

### ISSUE THREAD

**Issue by voozul** [doadin/Plexus#68]
I don't know what this means.. hope it helps!

111x Usage: self:SetVertexColor(color [, a])
[string "=[C]"]: in function `SetVertexColor'
[string "@SharedXML/Backdrop.lua"]:430: in function `SetBackdropBorderColor'
[string "@Plexus/Indicators/Icon.lua"]:183: in function `Reset'
[string "@Plexus/Frame.lua"]:101: in function `ResetAllIndicators'
[string "@Plexus/Frame.lua"]:1399: in function `UpdateIndicators'
[string "@Plexus/Frame.lua"]:1356: in function `?'
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Plexus/Status.lua"]:455: in function `Reset'
[string "@Plexus/Core.lua"]:800: in function `ResetModules'

**Comment by doadin** [comment]
Do you know what was happening at the time the error occurred?

**Comment by voozul** [comment]
Sorry I don't, it might be from a while ago, I just happened to check bugsack before logging off and saw it. Willl post if it happens again.
