### ISSUE TITLE
[Bug] Frames not properly saving position with very low UIscale.

### ISSUE THREAD

**Issue by Mir-d0** [doadin/Plexus#72]
**Describe the bug**
When playing on 3840x2160 with a UIscale below what the game natively supports, in my case 0.355... however I have tried with a wide range of scales and the issue remains, the saved position of the frames either aren't saved properly or aren't first loaded properly.

This happens on both reload and relog.

Switching addon profiles or changing the size of frames makes the frames move back to the desired position.

**To Reproduce**
1. Setting the UIscale, with the help off an addon, to anything below the default minimum. The lower the more noticable. 
2. Position your frames where you want them.
3. Reload or relog.
4. Frames are now in an unwanted position.

**Expected behavior**
The frames should stay in place.

**Screenshots**
https://gfycat.com/SelfassuredImmaterialKusimanse

Here's a recording showing position before and after a reload. 
Frames are anchored to the bottom of the screen.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v2.5.7
 - Game Version: Retail v10.0.2.47213

**Additional context**
I experienced a very similar problem with ShadowedUF which I did find a quick-fix for here: https://www.wowace.com/projects/shadowed-unit-frames/issues/1866

I imagine the issue is similar or maybe identical in nature and I have tried making my own fix for Plexus based on the info in the linked thread and issue#69, but I failed miserably.

**Comment by Mir-d0** [comment]
After updating the addon to v2.5.9 and doing a little bit of testing it seems the issue still persists.

**Comment by doadin** [comment]
closing as probabbly related to #69
