### ISSUE TITLE
[Bug] Visual Bug show incorrect status

### ISSUE THREAD

**Issue by Benflag** [doadin/Plexus#73]
Still happening in V.5.2.7

--

Visual bug happened in retail during a Mythic+ dungeon The Nokud Offensive in V.5.2.6

I was playing resto shaman
3 different teammate had status indicator for Earth Shield, and there was a lock in my party, but both the druid and the lock had Unending Resolve status indicator showing.

In both occasion, the person that never had the buff (the inexistant 3rd Earth Shield, and the druid inexistant Unending Resolve), their status indicator lasted for like 3 minutes, before going away by itself.

Earth Shield indicator is Indicator Top Left Corner
Unending Resolve indicator is Extra Icon: Top

--

Happened again in V.5.2.7

I was playing my resto shaman. Again 3 teammate had my earth shield. And one teammate warlock had a shaman defensive (Astral Shift).
Astral Shift indicator is Extra icon: Top

**Comment by Benflag** [comment]
From what I have seen, it's always a status that I track, at the indicator that I set it to.

The bug looks like it duplicated an ability that has been just casted by another player in the party. Ex: Playing resto shaman, having 2 earth shield up, I switch the earth shield around, and a 3rd (fake) earth shield still show as my status/indicator. Same thing for defensive I track in Extra Icon Top: someone will use a defensive (Astral Shift or Unending Resolve), and it will duplicated to another player (fake) and linger for 3 minutes before going away.

Only saw the bug in dungeon (Mythic plus key).

I was able to make the visual disappear by applying earth shield to the player that had the fake earthshield status indicator. And then casting it on another player (that way, removing earth shield from them) and it updated the status/indicator correctly.

**Comment by doadin** [comment]
Pushed out an update, just now please let me know if it still occurs with 2.5.9 .

**Comment by Benflag** [comment]
Have not tested yet in dungeon, but the update that was just pushed moved my UI slightly to the bottom right.

**Comment by doadin** [comment]
> Have not tested yet in dungeon, but the update that was just pushed moved my UI slightly to the bottom right.

Does it keep happening or just happened once?

**Comment by Benflag** [comment]
Yes, keep happening every reload. Always moved to the bottom and right like 1 inch.

**Comment by doadin** [comment]
Either of these issues still happening?

**Comment by Benflag** [comment]
I believe both are fixed.

Moving UI is fixed for sure.

Visual bug for incorrect status has not happened again since updating 3 days ago. 

Thanks :)
