### ISSUE TITLE
Can't find any way to track echo reversion in plexus

### ISSUE THREAD

**Issue by voozul** [doadin/Plexus#74]
I think its not possible to track buffs via their spell ID?

pres evoker has two different buffs both helpfully called reversion (the normal version and echo reversion).

This means its not possible (afaik) to track the two buffs seperately in plexus (you can only see if someone has reversion you can not set another indicator for the echo reversion. This is pretty bad for evokers as we need to see who has the second hot. Don't know if it would be possible for you to add allowing spell ID's as the two different reversions have two different spell IDs despite the same name.

This problem also applies to dream breath hot v dream breath echo hot.

**Comment by doadin** [comment]
v2.5.7 added statuses to support evoker echo abilities.

**Comment by doadin** [comment]
you can find them under status > auras > Echo: * ability name *
