### ISSUE TITLE
[Bug] lua error randomly when healing wotlk classic

### ISSUE THREAD

**Issue by ssateneth** [doadin/Plexus#75]
**Describe the bug**
I get a lua error when healing in alterac valley sometimes

**To Reproduce**
1. Go to alterac valley
2. do some heals in a large group
3. get error

**Expected behavior**
not get error

**Screenshots**
![image](https://user-images.githubusercontent.com/2127021/215297166-d7d1b64e-8d55-4d73-ac3a-5b60251ba5da.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 2.6.1-wrath.zip
 - Game Version wotlk classic 
 - 
**Additional context**
i dont know, it just gets lua error popup and its annoying

**Comment by doadin** [comment]
not an issue anymore?

**Comment by ssateneth** [comment]
i'll check it tomorrow.
