### ISSUE TITLE
[Bug] 4.3.4 (Whitemain.gg)

### ISSUE THREAD

**Issue by BritneyLozza** [doadin/Plexus#78]
**Describe the bug**
Doesn't work with 4.3.4

**To Reproduce**
Install addon and load the game

**Expected behavior**
I would expect the addon to load and show the bar in game.

**Desktop (please complete the following information):**
 - OS: Arch Linux w/ Wine
 - Version: Latest
 - Game Version: 4.3.4 (Whitemain.gg)

**Additional context**
Tried the wrath edition of this addon because it is closer to 4.3.4.

**Comment by doadin** [comment]
The game api is different from what it was in the past, because of this I would essentially have to support a 4th version of the game, sorry I can not do it.
