### ISSUE TITLE
wotlk v2.6.9 issues (only 8 out of 20 errors)

### ISSUE THREAD

**Issue by unco88** [doadin/Plexus#79]
lua errors from todays update:

3x Plexus/Core.lua:23: attempt to index field 'C_AddOns' (a nil value)
[string "@Plexus/Core.lua"]:23: in main chunk

Locals:
PLEXUS = "Plexus"
Plexus = <table> {
}
format = <function> defined =[C]:-1
strfind = <function> defined =[C]:-1
strjoin = <function> defined =[C]:-1
strlen = <function> defined =[C]:-1
strlower = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
strtrim = <function> defined =[C]:-1
strupper = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
GetBuildInfo = <function> defined =[C]:-1
CreateFrame = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'C_AddOns' (a nil value)"

3x Plexus/Roster.lua:25: attempt to call method 'NewModule' (a nil value)
[string "@Plexus/Roster.lua"]:25: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
tinsert = <function> defined =[C]:-1
GetInstanceInfo = <function> defined =[C]:-1
GetZonePVPInfo = <function> defined =[C]:-1
IsInRaid = <function> defined =[C]:-1
IsInGroup = <function> defined =[C]:-1
UnitExists = <function> defined =[C]:-1
UnitName = <function> defined =[C]:-1
UnitGUID = <function> defined =[C]:-1
UnitFullName = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "PlexusRoster"
(*temporary) = "attempt to call method 'NewModule' (a nil value)"

3x Plexus/Layout.lua:29: attempt to call method 'GetModule' (a nil value)
[string "@Plexus/Layout.lua"]:29: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
L = nil
floor = <function> defined =[C]:-1
format = <function> defined =[C]:-1
tinsert = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
strtrim = <function> defined =[C]:-1
C_Map = <table> {
 GetBestMapForUnit = <function> defined =[C]:-1
 GetMapArtHelpTextPosition = <function> defined =[C]:-1
 GetMapBannersForMap = <function> defined =[C]:-1
 GetMapHighlightInfoAtPosition = <function> defined =[C]:-1
 GetAreaInfo = <function> defined =[C]:-1
 GetMapArtLayers = <function> defined =[C]:-1
 RequestPreloadMap = <function> defined =[C]:-1
 GetBountySetIDForMap = <function> defined =[C]:-1
 GetWorldPosFromMapPos = <function> defined =[C]:-1
 GetMapLevels = <function> defined =[C]:-1
 GetMapInfoAtPosition = <function> defined =[C]:-1
 GetMapGroupMembersInfo = <function> defined =[C]:-1
 GetMapArtLayerTextures = <function> defined =[C]:-1
 GetMapArtBackgroundAtlas = <function> defined =[C]:-1
 MapHasArt = <function> defined =[C]:-1
 GetMapRectOnMap = <function> defined =[C]:-1
 GetMapPosFromWorldPos = <function> defined =[C]:-1
 GetPlayerMapPosition = <function> defined =[C]:-1
 GetMapGroupID = <function> defined =[C]:-1
 GetMapDisplayInfo = <function> defined =[C]:-1
 GetMapInfo = <function> defined =[C]:-1
 GetMapChildrenInfo = <function> defined =[C]:-1
 GetMapLinksForMap = <function> defined =[C]:-1
 GetFallbackWorldMapID = <function> defined =[C]:-1
 GetMapArtID = <function> defined =[C]:-1
}
CreateFrame = <function> defined =[C]:-1
GameTooltip = GameTooltip {
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 NineSlice = Frame {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:199
 0 = <userdata>
 updateTooltip = 0.200000
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 shoppingTooltips = <table> {
 }
 TopOverlay = Texture {
 }
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:187
 layoutType = "TooltipDefaultLayout"
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
}
GetInstanceInfo = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
InCombatLockdown = <function> defined =[C]:-1
IsAltKeyDown = <function> defined =[C]:-1
SlashCmdList = <table> {
 DEADLYBOSSMODSBREAK = <function> defined @DBM-Core/modules/Commands.lua:136
 BAGNON_BOE_LABEL = <function> defined @Bagnon_BoE/defaults.lua:36
 PLAYEDCLASS = <function> defined @Details/functions/slash.lua:16
 GETPOINT = <function> defined @ElvUI/Core/Developer/Frame.lua:50
 RELOADUI = <function> defined @SharedXML/InterfaceUtil.lua:1
 CVAR = <function> defined @AdvancedInterfaceOptions/browser.lua:377
 LEATRIX_PLUS_RL = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:15670
 DEADLYBOSSMODSPULL = <function> defined @DBM-Core/modules/Commands.lua:132
 DEADLYBOSSMODSDWAY = <function> defined @DBM-Core/DBM-Arrow.lua:277
 OmniCC = <function> defined @OmniCC/main.lua:32
 DBMRRANGE = <function> defined @DBM-Core/DBM-RangeCheck.lua:990
 DBMHUDAR = <function> defined @DBM-Core/DBM-HudMap.lua:1448
 DETAILS = <function> defined @Details/functions/slash.lua:37
 Leatrix_Plus = <function> defined @Leatrix_Plus/Leatrix_Plus.lua:15660
 NOVALUAONCMD = <function> defined @NovaInstanceTracker/NovaInstanceTracker.lua:649
 ACECONSOLE_GARGUL = <function> defined @Gargul/bootstrap.lua:180
 DEADLYBOSSMODS = <function> defined @DBM-Core/modules/Commands.lua:148
 BugGrabber = <function> defined @!BugGrabber/BugGrabber.lua:151
 DEVCON = <function> de
 
 3x Plexus/Layouts.lua:15: attempt to call method 'GetModule' (a nil value)
[string "@Plexus/Layouts.lua"]:15: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
L = nil
GetNumGroupMembers = <function> defined =[C]:-1
GetRaidRosterInfo = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "PlexusLayout"
(*temporary) = "attempt to call method 'GetModule' (a nil value)"

3x Plexus/Frame.lua:28: attempt to call method 'NewModule' (a nil value)
[string "@Plexus/Frame.lua"]:28: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
L = nil
format = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
InCombatLockdown = <function> defined =[C]:-1
GetTime = <function> defined =[C]:-1
UnitExists = <function> defined =[C]:-1
UnitGUID = <function> defined =[C]:-1
UnitInRange = <function> defined =[C]:-1
UnitIsDeadOrGhost = <function> defined =[C]:-1
UnitIsUnit = <function> defined =[C]:-1
UnitName = <function> defined =[C]:-1
PlexusStatus = nil
PlexusStatusRange = nil
Media = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 SetDefault = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:293
 GetDefault = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:289
 LOCALE_BIT_ruRU = 2
 UnregisterAllCallbacks = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 SetGlobal = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:280
 GetGlobal = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:276
 List = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:266
 HashTable = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:262
 MediaTable = <table> {
 }
 RegisterCallback = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 IsValid = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:258
 LOCALE_BIT_zhCN = 4
 UnregisterCallback = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Fetch = <function> defined @ElvUI_Libraries/Core/LibSharedMedia-3.0/LibSharedMedia-3.0.lua:251
 DefaultMedia = <table> {
 }
 Register = <function> defined =[C]:-1
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "PlexusFrame"
(*temporary) = "AceBucket-3.0"
(*temporary) = "AceTimer-3.0"
(*temporary) = "attempt to call method 'NewModule' (a nil value)"

3x Plexus/Status.lua:16: attempt to call method 'GetModule' (a nil value)
[string "@Plexus/Status.lua"]:16: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
L = nil
FillLocalizedClassList = <function> defined =[C]:-1
UnitClass = <function> defined =[C]:-1
UnitCreatureType = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "PlexusRoster"
(*temporary) = "attempt to call method 'GetModule' (a nil value)"

3x Plexus/Help.lua:97: attempt to index field 'options' (a nil value)
[string "@Plexus/Help.lua"]:97: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
L = nil
format = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
strlen = <function> defined =[C]:-1
helpText = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
(*temporary) = nil
(*temporary) = "enUS"
(*temporary) = <table> {
 1 = "Need more help?"
 2 = "If your question is not answered in this Help section, here are some other places you can get help with Plexus:"
 3 = "{Bug Reports & Feature Requests}"
 4 = "Please use the links at the top of Plexus's download page to report bugs and request features in the ticket tracker. This keeps all reports and requests in one place, so the developers can easily keep track of what needs to be done."
 5 = "{Questions & Comments}"
 order = 3
}
(*temporary) = <table> {
 1 = "Adding new buffs & debuffs"
 2 = "Plexus can show any buff or debuff, not just the ones that are set up by default."
 3 = "To add a new buff, go to the {Status} tab, select the {Auras} category in the list on the left, find the {Add new Buff} text box, type the name of the buff you want to add, and press Enter or click the {Okay} button."
 4 = "To add a debuff, type in the {Add new Debuff} box instead."
 5 = "Once you've added your buff or debuff, a new status will appear for it under the {Auras} category to the left. You can configure it just like the built-in buffs and debuffs, by changing its color, priority, text, and other options."
 6 = "You can also assign it to any indicator on the {Indicators} tab."
}
(*temporary) = <table> {
 1 = "Incoming heals"
 2 = "Information about incoming heals comes directly from the game client. Sometimes, the game client sends the wrong information, or no information at all."
 3 = "Plexus has no way to know if the healing amounts it gets are correct, or if there's healing incoming that the game client isn't telling it about."
 4 = "If you notice that a particular spell never triggers the {Incoming Heals} status, or always shows the wrong amount, please report the problem to Blizzard on the official Bug Report forums so they can fix it!"
}
(*temporary) = <table> {
 1 = "Incoming HoTs"
 2 = "The game doesn't distinguish between direct healing and periodic healing (HoTs), so Plexus has to make assumptions based on the heal size to filter out HoT ticks."
 3 = "By default, any incoming healing for less than 10% of the unit's total health is assumed to be from a HoT, and ignored. You can change this under {Status} > {Incoming heals} > {Minimum Value}."
}
(*temporary) = <table> {
 1 = "Credits"
 2 = "Plexus is a Grid fork, Grid was originally conceived and written by {Maia} and {Pastamancer} in late 2006. {Phanx} has been the primary developer since late 2009."
 3 = "{Jerry} wrote the original pet support code. {Mikk} designed the icon. {jlam} added some advanced options for auras. {Greltok} has helped a lot with bugfixing."
 4 = "Finally, lots of people have contributed translations; see the download page for a full list! And has since been continued and improved on for retail and classic by {Doadin}"
 order = -1
}
(*temporary) = "Credits"
(*temporary) = "Plexus is a Grid fork, Grid was originally conceived and written by {Maia} and {Pastamancer} in late 2006. {Phanx} has been the primary developer since late 2009."
(*temporary) = "{Jerry} wrote the original pet support code. {Mikk} designed the icon. {jlam} added some advanced options for auras. {Greltok} has helped a lot with bugfixing."
(*temporary) = "Finally, lots of people have contributed translations; see the download page for a full list! And has since been continued and improved on for retail and classic by {Doadin}"
(*temporary) = "Plexus uses a priority system to let you show more information in less space. You can assign two statuses to the same indicator, and then when they're both active, only the one with the higher priority will be shown."
(*temporary) = "For example, if you're a priest, you might assign Power Word: Shield (yellow, high priori

3x Plexus/Indicators/Alpha.lua:10: attempt to call method 'GetModule' (a nil value)
[string "@Plexus/Indicators/Alpha.lua"]:10: in main chunk

Locals:
_ = "Plexus"
Plexus = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "PlexusFrame"
(*temporary) = "attempt to call method 'GetModule' (a nil value)"

**Comment by sjwoodr** [comment]
Similar errors in classic era ... plexus 11 lua errors at login

**Comment by doadin** [comment]
All these error come from the core not loading. I have pushed out a new build just now(may take a while to come through curseforge if you use that) v2.7.0 or newer is what you want to look for. Sorry for the inconvenience.
