### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by McGratton** [doadin/Plexus#8]
Hi There,

I'm very new to this sort of thing so I hope I'm submitting this correctly. I keep getting this LUA error which appears to be related to Plexus as far as I can tell, but may be wrong. Here's what it says:

Date: 2020-02-26 19:30:06
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Plexus\Layout.lua line 1117:
   script ran too long
Debug:
   (tail call): ?
   Plexus\Layout.lua:1117: LoadLayout()
   Plexus\Layout.lua:966: ReloadLayout()
   Plexus\Layouts.lua:254: UpdateLayouts()
   Plexus\Layout.lua:1156: UpdateSize()
   Plexus\Layout.lua:699: ?()
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: SendMessage()
   Plexus\Roster.lua:245: ?()
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ons\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...LibThreatClassic2\Libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...LibThreatClassic2\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ClassicCastbars, vv1.2.7
  ClassicCastbarsOptions, v
  DBMCore, v1.13.38
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  DejaClassicStats, v1303r001
  DruidBarClassic, v0.7.7
  GatherMate2, v1.45.5
  HHTD, v2.4.9.4
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixPlus, v1.13.50
  LoseControl, v1.03
  NameplateCCnTrinket, v11303-2
  OmniCC, v8.3.5
  Plexus, vv1.9.0
  Questie, v5.7.2
  RealMobHealth, v2.18
  Recount, vv1.13.3c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.3.1
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=2a3)

Any help with this would be greatly appreciated.
Thanks!

**Comment by doadin** [comment]
Yes, I believe this issue comes from loading a lot of players such as joining a 40 man raid. I'm aware and working on it, haven't found a solution yet...

**Comment by McGratton** [comment]
Ok,thanks for the heads up. Good luck on a solution.

**Comment by doadin** [comment]
closing as repeat of https://github.com/doadin/Plexus/issues/30

**Comment by doadin** [comment]
I hope you stuck around to see it finally fixed :)
