### ISSUE TITLE
[Bug] mini map button missing?

### ISSUE THREAD

**Issue by voozul** [doadin/Plexus#80]
2.7.0 the mini map button seems to have gone and I can't find any option to put it back?
I might have done something dumb.
ty!

**Comment by doadin** [comment]
In retail I have switched to useing the [addon compartment.](https://wowpedia.fandom.com/wiki/Addon_compartment)

**Comment by doadin** [comment]
If you have a addon that modifies the minimap the addon compartment maybe in a different place.

**Comment by voozul** [comment]
Oh! ty! I didn't even know that was a thing.. found it there as you said:)
Great addon, thanks for all ur work on it
