### ISSUE TITLE
[Bug] Unable to change border indicator thickness.

### ISSUE THREAD

**Issue by dabadoo** [doadin/Plexus#83]
**Describe the bug**
I'm trying to make my border indicator thicker. For target select and aggro. I go to Frame->General->Border Size and slide it from 1 to 9.

**Expected behavior**
I would expect this to make my border indicators bigger but what happens is that a black border grows bigger instead. My border indicator stays the same.

**Screenshots**

Border size set to 1
![size 1](https://github.com/doadin/Plexus/assets/25304408/1d23a3ed-2ddd-48bb-b087-1237eb532422)

Border size set to max (9)
![size 9](https://github.com/doadin/Plexus/assets/25304408/9865f343-1644-4bc8-a43a-3afb80cb88a3)

**Desktop (please complete the following information):**
 - Windows
 - 2.7.7
 - ERA

**Comment by dabadoo** [comment]
I've found the following:
If I go to Frame->General->Border Size and slide to make the border thicker. As shown in the picture above the black frame is all that grows.
But. If then go to files Plexus/Indicators/Border.lua Line:15
and change edgeSize to something higher than 1, it works. The black border is still bigger when the indicator isn't active. But now when I target or have aggro the border colored border indicator has filled out the black space.

**Comment by doadin** [comment]
@dabadoo Sorry for my late responce, but yes that is how the code is setup to work this is not a bug. They are two different things border around the frame and a indicator that goes around the frame. the setting in general is for the border not the indicator.

**Comment by dabadoo** [comment]
I see. I was a bit confused since it says "Adjust the size of the border indicators." when hovered over.
I did find it strange that I was somehow the first one to stumble upon this "issue".
Gonna close the issue. But I think it would be a good enhancement to be able to change the size of the border indicator, just like you can change the other indicators.
Cheers!
