### ISSUE TITLE
Error when loading the game

### ISSUE THREAD

**Issue by Hallelujah001** [doadin/Plexus#9]
Date: 2020-03-15 09:18:10
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Plexus\Statuses\Summon.lua line 20:
   attempt to index field 'SummonStatus' (a nil value)
Debug:
   Plexus\Statuses\Summon.lua:20: in main chunk
Locals:
_ = "Plexus"
Plexus = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\Plexus\Core.lua:772
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SetupOptions = <function> defined @Interface\AddOns\Plexus\Core.lua:582
 NewStatusModule = <function> defined @Interface\AddOns\Plexus\Status.lua:200
 defaultModuleLibraries = <table> {
 }
 SetDebuggingEnabled = <function> defined @Interface\AddOns\Plexus\Core.lua:101
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\Plexus\Core.lua:766
 UnregisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 ToggleOptions = <function> defined @Interface\AddOns\Plexus\Core.lua:669
 options = <table> {
 }
 defaultModulePrototype = <table> {
 }
 Printf = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\Plexus\Core.lua:761
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 ResetModules = <function> defined @Interface\AddOns\Plexus\Core.lua:749
 DisableModules = <function> defined @Interface\AddOns\Plexus\Core.lua:743
 EnableModules = <function> defined @Interface\AddOns\Plexus\Core.lua:737
 name = "Plexus"
 RegisterModule = <function> defined @Interface\AddOns\Plexus\Core.lua:721
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 OnModuleCreated = <function> defined @Interface\AddOns\Plexus\Core.lua:708
 DisableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 OnEnable = <function> defined @Interface\AddOns\Plexus\Core.lua:538
 defaultDB = <table> {
 }
 ADDON_LOADED = <function> defined @Interface\AddOns\Plexus\Core.lua:780
 OnProfileEnable = <function> defined @Interface\AddOns\Plexus\Core.lua:566
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OnDisable = <function> defined @Interface\AddOns\Plexus\Core.lua:558
 GetDebuggingOptions = <function> defined @Interface\AddOns\Plexus\Core.lua:696
 OnInitialize = <function> defined @Interface\AddOns\Plexus\Core.lua:474
 IsClassicWow = <function> defined @Interface\AddOns\Plexus\Core.lua:308
 IsModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 modulePrototype = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 ImportProfile = <function> defined @Interface\AddOns\Plexus\Core.lua:254
 ExportProfile = <function> defined @Interface\AddOns\Plexus\Core.lua:232
 SetEnabledState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDebuggingEnabled = <function> defined @Interface\AddOns\Plexus\Core.lua:82
 enabledState = true
 Debug = <function> defined @Interface\AddOns\Plexus\Core.lua:66
 RegisterEvent = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 L = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.45.01
  AtlasClassicWoW, vv1.45.00
  AtlasLootClassic, vv1.4.6
  AtlasLootClassicData, vv1.4.6
  AtlasLootClassicDungeonsAndRaids, vv1.4.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  ClassicCastbars, v1.0.1
  ClassicCastbarsOptions, v
  ClassicLFG, v1.1.3
  Clique, vv11302-1.0.0
  DBMCore, v1.13.38
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r037
  Dismounter, v1.2.1
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  ItemRack, v
  PallyPower, vv1.1k-classic
  Plexus, vv1.9.4
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=46f)

**Comment by doadin** [comment]
From the looks of the names of the other addons your using your on classic, the classic version of plexus doesn't have the summon status module enabled, please install the classic version.

**Comment by Hallelujah001** [comment]
Where can I find the "Classic" version of Plexus? Thanks in advance.

**Comment by doadin** [comment]
https://www.curseforge.com/wow/addons/plexus
https://www.curseforge.com/wow/addons/plexus/files/2902759
or the twitch client.

**Comment by doadin** [comment]
If you are using the twitch client sometimes it can misinterpret the WoW client as retail restarting it might help.
