### ISSUE TITLE
[Bug] [SoD] Lua error on casting Regrowth or Rejuvenation when druid knows "Enhanced Restoration"

### ISSUE THREAD

**Issue by ssateneth** [doadin/Plexus#90]
**Describe the bug**
A lua error pops up. That's it.

**To Reproduce**
1. Play Season of Discovery.
2. Group with or play a druid that knows "Enhanced Restoration"
3. Have druid cast Regrowrth
4. LUA error happens

**Expected behavior**
Don't have LUA error

**Screenshots**
![image](https://github.com/doadin/Plexus/assets/2127021/b7760da5-ac74-4d2b-85ee-e6366ca30ae6)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version [e.g. v1.5.6] plexus 2.9.6 classic
 - Game Version [e.g. Retail v8.3.0] classic wow season of discovery 1.15.1.53247

**Additional context**
Message: ...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:818: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Sun Feb 11 17:37:58 2024
Count: 2
Stack: ...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:818: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:818: in function <...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:807>
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:967: in function <...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:965>
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:2710: in function `?'
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:3352: in function <...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3350>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by doadin** [comment]
I unfortunatly don't play classic in any form, so I am unable to fix issues with LibHealComm-4.0 myself. I have pushed an update that will hopefully not make the error pop up, however if LibHealComm-4.0 does not have the data for the spell it is not going to give accurate heal prediction, for the missing spells.  This issue has already been brought up https://github.com/Azilroka/LibHealComm-4.0/issues , hopefully someone will update LibHealComm-4.0.
