### ISSUE TITLE
[Bug] [SoD] Plexus window disappears when in strangethorn vale with blood moon event active

### ISSUE THREAD

**Issue by ssateneth** [doadin/Plexus#91]
**Describe the bug**
When the blood moon event is active in STV and you are in STV, plexus unit frames will disappear and borders show a weird stacked overlapping graphic

**To Reproduce**
1. Go to STV
2. Wait for blood moon event
3. When event active, plexus UI breaks

**Expected behavior**
The plexus UI should stay normal and not break

**Screenshots**
I will get one later since the event isnt active now.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version [e.g. v1.5.6] plexus 2.9.6 classic
 - Game Version [e.g. Retail v8.3.0] classic wow season of discovery 1.15.1.53247

**Additional context**

**Comment by ssateneth** [comment]
![image](https://github.com/doadin/Plexus/assets/2127021/e2315b89-c104-4ad2-8ca5-7ca086932ecf)
![image](https://github.com/doadin/Plexus/assets/2127021/aec8c8e4-ac6d-4fcf-b115-67bfa89d8588)

**Comment by doadin** [comment]
Is there no lua error?

**Comment by ssateneth** [comment]
i didnt see any. This also happens when flying over or being in wintergrasp in WotLK classic.

**Comment by doadin** [comment]
Yea sorry I unfortunately don't play classic or wrath so I rely a lot on user reports. I will look into this.

**Comment by doadin** [comment]
I have pushed this change https://github.com/doadin/Plexus/commit/03538bd13fd814170cc781980c26af4dc86aba83 as release v3.0.1 , this change fixed wintergrasp in retail, let me know if it is still an issue in classic wrath wintergrasp  and for classic blood moon event.

**Comment by ssateneth** [comment]
I was able to confirm last night while in STV during event that the Plexus window remains usable now. It turned into 40 man raid mode while solo but it's better than nothing (I'm sure I can change that in settings). I consider the matter closed.

**Comment by ssateneth** [comment]
actually, need to re open this. I was in a 4 person party just now and the UI disappears as if I were on the bugged version when solo. I rolled back to a random old version 2.9.7 (i needed to do it quick) and it worked again while in a group.

**Comment by doadin** [comment]
so it is fine still when solo, but not while in a group?

**Comment by ssateneth** [comment]
Correct. I got the same graphic glitch when in a 4 man party group when the STV event activated and no unit frames were showing. Rolled back to old version, party UI was restored.

**Comment by doadin** [comment]
@ssateneth hmmm unfortunatly, I don't think I know anyone that plays that I could get into a group with.

**Comment by doadin** [comment]
<img width="714" alt="image" src="https://github.com/doadin/Plexus/assets/2148359/466086bf-574d-4f01-83bb-89a3af656996">
with 3.0.4 this is what i am seeing. in a group with 1 other person(found someone random to inv)

**Comment by ssateneth** [comment]
maybe i'll have to share you my plexus profile then, not sure why it works for them and not for me. it might be some setting that i changed

**Comment by doadin** [comment]
<img width="356" alt="image" src="https://github.com/doadin/Plexus/assets/2148359/8f466c48-a515-4417-bb69-442e0531e716">

**Comment by doadin** [comment]
from what i can tell 3.0.4 works both during and after blood moonwhile in group with 1 other person. and 3.0.3 and 3.0.2 work at least after bloodmoon did not have a chance to test during.

**Comment by doadin** [comment]
yea hard to test things like this.

**Comment by doadin** [comment]
is this still an issue or is it fixed?

**Comment by ssateneth** [comment]
I haven't had an issue yet as I tend to avoid STV/battle zones, so consider the matter closed for the foreseeable future.
