### ISSUE TITLE
[Bug] shaman cant dispel poison in cata

### ISSUE THREAD

**Issue by rdmqwerty** [doadin/Plexus#93]
**Describe the bug**
when setting up a debuff indicator with "show only if dispellable", poisons show up when playing a shaman in cata. i believe that the cata changes removed the ability for shamans to dispel poisons. they can do curse by default and curse + magic with a resto talent

**To Reproduce**
1. Go to "options - status"
2. Click on "debuff type: poison"
3. Check off "show only if dispellable"
4. Setup an indicator for this status
5. find a monster to poison you
6. observe the indicator

**Expected behavior**
the "show if only dispellable" logic should only show when playing a class that can dispel the debuff

**Comment by rdmqwerty** [comment]
this might also be the case for diseases too. but i havent seen one to test it yet

**Comment by doadin** [comment]
dispels should be up to date now in v3.1.5 , let me know if they are still inaccurate after updating to that, thanks!

**Comment by rdmqwerty** [comment]
looks like they are working correctly from what ive seen
