### ISSUE TITLE
[Bug] table index is nil

### ISSUE THREAD

**Issue by rdmqwerty** [doadin/Plexus#94]
**Describe the bug**
when i log into my priest, i get an error message coming from plexus

**To Reproduce**
1. log in as a priest
2. See error

**Expected behavior**
i would not expect to see an error message

**Desktop (please complete the following information):**
 - Version - Plexus-v3.1.5-cata
 - Game Version - cataclysm

**Additional context**
here is what the error message says:
`1x ...dOns/Plexus/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua:1537: table index is nil
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:1537: in function <...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:1481>
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3454: in function `OnInitialize'
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3594: in function `?'
[string "@Interface/AddOns/Plexus/Libs/LibHealComm-4.0-117/LibHealComm-4.0.lua"]:3573: in function <...dOns/Plexus/Libs/LibHealComm-4.0/LibHealComm-4.0.lua:3569>`

im not 100% sure what LibHealComm is, but i think this error might be causing issues with showing incoming heals on plexus. i dont see any green numbers when casting heals

**Comment by doadin** [comment]
Fixed: https://github.com/doadin/Plexus/commit/6c5ab7075758028da38d421bfdf7e43e6aa2cc2f
