### ISSUE TITLE
[Bug] Auras (and their indicators) not working at all

### ISSUE THREAD

**Issue by Lunaeria** [doadin/Plexus#96]
Hello! Everything seemed to be fine with Plexus for the prepatch, but I noticed none of my indicators were showing up when I cast a spell on someone. I checked the Indicators tab, and none of my spells were visible there; upon investigating further, I also found that the entire "Auras" category was missing from the Status tab.

I'm getting the following errors:

```
53x Plexus/Statuses/Auras.lua:493: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Plexus/Statuses/Auras.lua"]:493: in main chunk

Locals:
(*temporary) = "Buff: %s"
(*temporary) = nil
(*temporary) = "string expected, got nil"
```

**Comment by doadin** [comment]
fixed: 95d55c9496461dc4974a3d795b7f4ab30ad70118
