### ISSUE TITLE
[Bug] LUA Error due to Essence Font removal

### ISSUE THREAD

**Issue by Aurilia-Gilneas** [doadin/Plexus#97]
The monk spell "Essence Font" no longer exists as of 11.0.  This is causing an LUA error, as the spell_names lookup function now returns a nil value for that spell.

BugSack:

Plexus/Statuses/Auras.lua:493: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Plexus/Statuses/Auras.lua"]:493: in main chunk

Locals:
(*temporary) = "Buff: %s"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by doadin** [comment]
fixed: 95d55c9496461dc4974a3d795b7f4ab30ad70118
