### ISSUE TITLE
[Bug] all indicators/tracking of debuffs/buffs/spells gone

### ISSUE THREAD

**Issue by voozul** [doadin/Plexus#98]
**Describe the bug**
All the buffs and debuffs i've added over the years are all gone from plexus as of patch day, all tracking has gone.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] 10 pro
 - Version [e.g. v1.5.6] 22h2
 - Game Version retail 11.0.0 / plexus version 3.2.4

**Comment by doadin** [comment]
v3.2.5 has a fix for aura code have you tried this update?
